//
// Generated file, do not edit! Created by nedtool 5.4 from netmsg.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __FIFO_NETMSG_M_H
#define __FIFO_NETMSG_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0504
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif


namespace fifo {

/**
 * Class generated from <tt>netmsg.msg:21</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * message Netmsg
 * {
 *     int destination;
 * }
 * </pre>
 */
class Netmsg : public ::omnetpp::cMessage
{
  protected:
    int destination;

  private:
    void copy(const Netmsg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Netmsg&);

  public:
    Netmsg(const char *name=nullptr, short kind=0);
    Netmsg(const Netmsg& other);
    virtual ~Netmsg();
    Netmsg& operator=(const Netmsg& other);
    virtual Netmsg *dup() const override {return new Netmsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getDestination() const;
    virtual void setDestination(int destination);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Netmsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Netmsg& obj) {obj.parsimUnpack(b);}

} // namespace fifo

#endif // ifndef __FIFO_NETMSG_M_H

